import {
  assistantAttachmentMetadataSchema,
  type AssistantAttachmentMetadata,
} from "@/lib/validators/assistant";

const ALLOWED_ASSISTANT_FIELDS = new Set([
  "id",
  "key",
  "name",
  "firstName",
  "lastName",
  "studentName",
  "subjectName",
  "packageName",
  "tutorName",
  "email",
  "emailAddress",
  "recipientEmail",
  "phone",
  "avatarUrl",
  "description",
  "body",
  "notes",
  "status",
  "role",
  "type",
  "kind",
  "method",
  "relationship",
  "isPrimary",
  "isActive",
  "isPaid",
  "isOverdue",
  "isDueThisMonth",
  "temporary",
  "deleted",
  "removed",
  "updated",
  "created",
  "sent",
  "failed",
  "success",
  "invited",
  "revoked",
  "cancelled",
  "rescheduled",
  "ended",
  "hasMore",
  "href",
  "virtual",
  "isDepleted",
  "dob",
  "dateOfBirth",
  "ageYears",
  "school",
  "gradeLevel",
  "createdAt",
  "updatedAt",
  "startDate",
  "endDate",
  "startsOn",
  "endsOn",
  "scheduledFor",
  "paidAt",
  "validFrom",
  "validUntil",
  "occurrenceFor",
  "recurrenceOccurrenceFor",
  "month",
  "monthLabel",
  "coversMonth",
  "from",
  "to",
  "start",
  "end",
  "endExclusive",
  "timeZone",
  "startTime",
  "dayOfWeek",
  "daysOfWeek",
  "durationMinutes",
  "intervalWeeks",
  "room",
  "color",
  "amount",
  "balance",
  "basePrice",
  "priceAtEnrollment",
  "customPriceOverride",
  "hourlyRate",
  "earnings",
  "totalEarnings",
  "hours",
  "totalHours",
  "value",
  "billingPeriod",
  "billingPeriodIndex",
  "lessonType",
  "sessionsPerWeek",
  "usesRemaining",
  "billable",
  "total",
  "count",
  "totalSessions",
  "usedThisWeek",
  "remaining",
  "thisMonthTotal",
  "thisMonthCount",
  "lastMonthTotal",
  "page",
  "pageSize",
  "limit",
  "matchingStudentCount",
  "rankedStudentCount",
  "missingDateOfBirthCount",
  "activeStudentCount",
  "rulesCreated",
  "materializedSessions",
  "sortBy",
  "sortOrder",
  "studentId",
  "guardianId",
  "tutorId",
  "subjectId",
  "packageId",
  "enrollmentId",
  "groupId",
  "sessionId",
  "recurrenceRuleId",
  "ruleId",
  "paymentId",
  "discountId",
  "invitationId",
  "adminId",
  "subjectIds",
  "studentIds",
  "students",
  "student",
  "guardians",
  "guardian",
  "primaryGuardian",
  "tutors",
  "tutor",
  "subjects",
  "subject",
  "packages",
  "package",
  "enrollments",
  "enrollment",
  "discounts",
  "discount",
  "groups",
  "group",
  "sessions",
  "session",
  "realSessions",
  "virtualSessions",
  "summaries",
  "paidMonths",
  "subscriptionEnrollmentIds",
  "sessionAttendance",
  "attendance",
  "attendances",
  "payments",
  "payment",
  "rules",
  "preview",
  "admins",
  "pendingInvitations",
  "todaySessions",
  "tomorrowSessions",
  "upcomingEndings",
  "tutorCounts",
  "unpaidStudents",
  "weeklySessionsByDay",
  "monthlyRevenue",
  "day",
  "revenue",
  "thisMonth",
  "lastMonth",
  "allTime",
  "results",
]);

export function minimizeAssistantDto(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(minimizeAssistantDto);
  }
  if (!value || typeof value !== "object") {
    return value;
  }

  return Object.fromEntries(
    Object.entries(value)
      .filter(([key]) => ALLOWED_ASSISTANT_FIELDS.has(key))
      .map(([key, item]) => [key, minimizeAssistantDto(item)]),
  );
}

export function parseAssistantAttachmentMetadata(
  value: unknown,
): AssistantAttachmentMetadata[] {
  const parsed = assistantAttachmentMetadataSchema.array().safeParse(value);
  return parsed.success ? parsed.data : [];
}
